# Generated by Django 4.2.10 on 2024-02-18 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CicloTransacciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ciclo_transacciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DeudaRecaudador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('reten', models.CharField(blank=True, max_length=50, null=True)),
                ('turno', models.CharField(blank=True, max_length=40, null=True)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('nombre_usuario', models.CharField(blank=True, max_length=100, null=True)),
                ('regional', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'db_table': 'deuda_recaudador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IntentosCierre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_caja_carril', models.SmallIntegerField(blank=True, null=True)),
                ('intentos_cierre', models.SmallIntegerField(blank=True, null=True)),
                ('id_recaudador', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'intentos_cierre',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id_menu', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('ruta', models.CharField(blank=True, max_length=255, null=True)),
                ('icono', models.CharField(blank=True, max_length=255, null=True)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('fid_menu', models.IntegerField(blank=True, null=True)),
                ('es_menu', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'menu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MenuGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'menu_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_categoria', models.SmallIntegerField(blank=True, null=True)),
                ('nombre_categoria', models.CharField(blank=True, max_length=100, null=True)),
                ('importe', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cantidad', models.SmallIntegerField(blank=True, null=True)),
                ('importe_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'monitor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MonitorTotal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha_operaciones', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'monitor_total',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReceptorDatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_leido', models.CharField(blank=True, db_comment='codigo recibido de los dispositivos', max_length=100, null=True)),
                ('placa', models.CharField(blank=True, max_length=20, null=True)),
                ('numero_ejes_inicio', models.SmallIntegerField(blank=True, null=True)),
                ('numero_ejes_salida', models.SmallIntegerField(blank=True, null=True)),
                ('ancho_vehiculo', models.CharField(blank=True, max_length=100, null=True)),
                ('alto_vehiculo', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_remolques', models.SmallIntegerField(blank=True, null=True)),
                ('clase_vehiculo', models.CharField(blank=True, max_length=100, null=True)),
                ('imagen_frontal', models.CharField(blank=True, max_length=100, null=True)),
                ('imagen_lateral', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.BooleanField(blank=True, null=True)),
                ('tipo', models.SmallIntegerField(blank=True, db_comment='si es tag o roceta', null=True)),
            ],
            options={
                'db_table': 'receptor_datos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoContingencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=150)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tipo_contingencia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Turnos',
            fields=[
                ('id_turno', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=32, null=True)),
                ('horainicio', models.CharField(blank=True, max_length=6, null=True)),
                ('grupo_turno', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'turnos',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Ashift',
        ),
        migrations.DeleteModel(
            name='Atrset',
        ),
        migrations.DeleteModel(
            name='Contingencia',
        ),
    ]
